[package]
name = "input_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.58.0", features = [
    "Win32_System_Com",
    "Win32_UI_Accessibility",
    "Win32_System_Variant",
    "Win32_System_Ole",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }